### PR TITLE
Make the matconvnet to caffe script works well when the trained network is GPU type

### PR DESCRIPTION
**Pull request by mirsking**
Firstly convert trained network to CPU type.
Then finish the conversation.

### CODE REVIEW

**Comment by zoharby** [comment]
Hi, thanks for pointing this out!

Please check the commit I made in zoharby/matconvnet, I think it solves the problem with much less changes:
- filters,biases aren't needed since we copy them to weights and then use only weights.
- filtersMomentum, biasesMomentum aren't needed since they are used only for training and are not used at test time.

If the current version works well, then we'll keep it instead of the pull request. If not, let me know where it fails.

**Comment by mirsking** [comment]
No,  this version doesn't work. Because this script use the vl_simplenn.m which depends on vl_nnconv.
And vl_nnconv uses the filters and biases of the net.

You can see the error below

```
Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;


Error in convert_matconvnet_caffe (line 216)
    res = vl_simplenn(layer, dummy_data);
```

**Comment by zoharby** [comment]
Right, makes sense.

Merged your PR, thanks for contributing!

**Comment by mirsking** [comment]
Thank you for the merge.

**Pull request merged**
